FROM quay.io/centos/centos:stream10-development

MAINTAINER https://github.com/redhat-plumbers/dracut-rhel10

# prefer running tests with xfs
ENV TEST_FSTYPE=xfs
ENV container=docker

LABEL RUN="docker run -it --name NAME --privileged --ipc=host --net=host --pid=host -e NAME=NAME -e IMAGE=IMAGE IMAGE"

RUN echo 'export DRACUT_NO_XATTR=1 KVERSION=$(cd /lib/modules; ls -1 | tail -1)' > /etc/profile.d/dracut-test.sh

# Install needed packages for the dracut CI container
# FIXME: properly re-add dash once C10S EPEL is available
RUN dnf -y install --skip-broken --enablerepo crb --setopt=install_weak_deps=False \
    https://kojipkgs.fedoraproject.org//packages/dash/0.5.12/4.eln141/x86_64/dash-0.5.12-4.eln141.x86_64.rpm \
    https://kojipkgs.fedoraproject.org//packages/btrfs-progs/6.9.2/1.eln141/x86_64/btrfs-progs-6.9.2-1.eln141.x86_64.rpm \
    qemu-kvm \
    NetworkManager \
    asciidoc \
    bash-completion \
    bzip2 \
    cryptsetup \
    dbus-daemon \
    dhcp \
    e2fsprogs \
    gcc \
    git \
    iproute \
    iputils \
    iscsi-initiator-utils \
    kbd \
    kernel \
    kmod-devel \
    lvm2 \
    make \
    mdadm \
    nfs-utils \
    parted \
    pigz \
    rpm-build \
    squashfs-tools \
    strace \
    sudo \
    tar \
    tcpdump \
    wget \
    which \
    xz \
    btrfs-progs \
    dhcp-client \
    dhcp-server \
    nbd \
    qemu \
    scsi-target-utils \
    openssl-devel \
    ;
#    && dnf -y update && dnf clean all

# From Fedora container
# Install needed packages for the dracut CI container
RUN dnf -y install --skip-broken --enablerepo crb --setopt=install_weak_deps=False \
    asciidoc \
    bash-completion \
    bluez \
    btrfs-progs \
    bzip2 \
    cargo \
    cifs-utils \
    crypto-policies-scripts \
    cryptsetup \
    dbus-daemon \
    device-mapper-multipath \
    dhcp \
    dhcp-client \
    dhcp-server \
    dracut-live \
    e2fsprogs \
    erofs-utils \
    fcoe-utils \
    fuse3 \
    gcc \
    git \
    ignition \
    iproute \
    iputils \
    iscsi-initiator-utils \
    jq \
    kbd \
    kdump-utils \
    kernel \
    kmod-devel \
    libfido2 \
    libkcapi-hmaccalc \
    libselinux-utils \
    lvm2 \
    make \
    mdadm \
    memstrack \
    nbd \
    ndctl \
    NetworkManager \
    nfs-utils \
    nvme-cli \
    openssl-devel \
    parted \
    pcsc-lite \
    pigz \
    plymouth \
    qemu \
    qemu-kvm \
    rng-tools \
    rpm-build \
    rsyslog \
    scsi-target-utils \
    squashfs-tools \
    strace \
    sudo \
    swtpm \
    systemd-boot-unsigned \
    systemd-container \
    systemd-devel \
    systemd-resolved \
    systemd-ukify \
    tar \
    tcpdump \
    tpm2-tools \
    wget \
    which \
    xfsprogs \
    xorriso \
    xz \
    && dnf -y update && dnf clean all

# discard configurations that enforce an out-of-tree dracut module
# which would break test automation
# since this is a distro specific change, lets do it in the container
RUN \
  rm -rf /usr/lib/dracut/dracut.conf.d/50-nss-softokn.conf

# CentOS Stream ships only qemu-kvm, but it disables the KVM accel when it's not available
RUN \
    [[ -e /usr/bin/qemu-kvm ]] || ln -sf /usr/libexec/qemu-kvm /usr/bin/qemu-kvm ;\
    [[ -e /usr/bin/qemu-system-$(uname -m) ]] || ln -sv /usr/libexec/qemu-kvm /usr/bin/qemu-system-$(uname -m) ;\
;\
update-crypto-policies --no-reload --set FIPS
