name: Container
on:
    schedule:
        -  cron: '30 11 * * *'   # every day at 11:30 UTC
    push:
        branches: [ main ]
        paths:
            - 'test/container/**'
            - '.github/workflows/container.yml'
    pull_request:
        branches: [ main ]
        paths:
            - 'test/container/**'
            - '.github/workflows/container.yml'

permissions:
    packages: write
    contents: read

jobs:
    push_to_registry:
        name: ${{ matrix.config.tag }} on ${{ matrix.config.platform }}
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.config.dockerfile }}
            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { dockerfile: 'Dockerfile-CentOS-10-Stream',   tag: 'centos:stream10' }
        steps:
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3
                with:
                    platforms: ${{ matrix.config.platform }}
            -   name: Check out the repo
                uses: actions/checkout@v4
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: Set up env
                run: echo "repository_owner=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
            -   name: Build and Push Container
                uses: docker/build-push-action@v5
                with:
                    file: test/container/${{ matrix.config.dockerfile }}
                    tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.config.tag }}
                    push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
                    platforms: ${{ matrix.config.platform }}
