name: Integration Test

on:
    pull_request:
        branches: [ main ]

env:
    DEBUGFAIL: "${{ secrets.ACTIONS_STEP_DEBUG && 'rd.debug' }}"

jobs:
    basic:
        # run this test on all containers
        name: ${{ matrix.test }} on ${{ matrix.container }}
        runs-on: ubuntu-latest
        timeout-minutes: 45
        concurrency:
            group: basic-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}
            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                container: [
                        "centos:stream10",
                ]
                test: [
                        "01",
                ]
        container:
            image: ghcr.io/${{ github.repository_owner }}/${{ matrix.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v4
            -   name: "${{ matrix.container }} TEST-${{ matrix.test }}"
                run: ./tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
    network:
        name: ${{ matrix.test }} on ${{ matrix.container }} using ${{ matrix.network }}
        runs-on: ubuntu-latest
        timeout-minutes: 45
        concurrency:
            group: network-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}-${{ matrix.network }}
            cancel-in-progress: true
        strategy:
            matrix:
                container: [
                        "centos:stream10",
                ]
                network: [
                        "network",
                ]
                test: [
                        "20",
                        "40",
                        "50",
                        "60",
                ]
            fail-fast: false
        container:
            image: ghcr.io/redhat-plumbers/${{ matrix.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v4
            -   name: "${{ matrix.container }} TEST-${{ matrix.test }}"
                run: USE_NETWORK=${{ matrix.network }} ./tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
    systemd-networkd:
        name: ${{ matrix.test }} on ${{ matrix.container }} using ${{ matrix.network }}
        runs-on: ubuntu-latest
        timeout-minutes: 45
        concurrency:
            group: systemd-networkd-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}-${{ matrix.network }}
            cancel-in-progress: true
        strategy:
            matrix:
                container: [
                        "arch",
                ]
                network: [
                        "systemd-networkd",
                ]
                test: [
                        "35",
                        "40",
                ]
            fail-fast: false
        container:
            image: ghcr.io/redhat-plumbers/${{ matrix.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v4
            -   name: "${{ matrix.container }} TEST-${{ matrix.test }}"
                run: USE_NETWORK=${{ matrix.network }} ./tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
    extended:
        name: ${{ matrix.test }} on ${{ matrix.container }}
        runs-on: ubuntu-latest
        timeout-minutes: 45
        concurrency:
            group: extended-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}
            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                container: [
                        "centos:stream10",
                ]
                test: [
                        "02",
                        "03",
                        "04",
                        "10",
                        "11",
                        "12",
                        "13",
                        "14",
                        "15",
                        "16",
                        "17",
                        "18",
                        "62",
                        "98",
                ]
        container:
            image: ghcr.io/${{ github.repository_owner }}/${{ matrix.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v4
            -   name: "${{ matrix.container }} TEST-${{ matrix.test }}"
                run: ./tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
    dracut-cpio:
        name: ${{ matrix.test }} on ${{ matrix.container }}
        runs-on: ubuntu-latest
        timeout-minutes: 45
        concurrency:
            group: dracut-cpio-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}


            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                container: [
                        "centos:stream10",
                ]
                test: [
                        "20",
                        "30",
                        "35",
                        "40",
                        "50",
                        "60",
                ]
        container:
            image: ghcr.io/${{ github.repository_owner }}/${{ matrix.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: "${{ matrix.container }} TEST-${{ matrix.test }}"
                run: USE_NETWORK=${{ matrix.network }} ./tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
    network:
        # all nfs based on default networking
        name: ${{ matrix.test }} on ${{ matrix.container }}
        runs-on: ubuntu-latest
        timeout-minutes: 45
        concurrency:
            group: network-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}-${{ matrix.network }}
            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                container: [
                        "centos:stream10",
                ]
                test: [
                        "20",
                        "50",
                        "60",
                ]
                include:
                  - network: ""
        container:
            image: ghcr.io/${{ github.repository_owner }}/${{ matrix.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v4
            -   name: "${{ matrix.container }} TEST-${{ matrix.test }}"
                run: USE_NETWORK=${{ matrix.network }} ./tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
    network-iscsi:
        name: ${{ matrix.test }} on ${{ matrix.container }}
        runs-on: ubuntu-latest
        timeout-minutes: 45
        concurrency:
            group: network-iscsi-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}-${{ matrix.network }}
            cancel-in-progress: true
        strategy:
            # run tests sequentially
            max-parallel: 1
            fail-fast: false
            matrix:
                container: [
                        "centos:stream10",
                ]
                test: [ "30","35" ]
                include:
                  - network: ""
        container:
            image: ghcr.io/${{ github.repository_owner }}/${{ matrix.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v4
            -   name: "${{ matrix.container }} TEST-${{ matrix.test }}"
                run: USE_NETWORK=${{ matrix.network }} ./tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
    network-nbd:
        name: ${{ matrix.test }} on ${{ matrix.container }}
        runs-on: ubuntu-latest
        timeout-minutes: 45
        concurrency:
            group: network-nbd-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}-${{ matrix.network }}
            cancel-in-progress: true
        strategy:
            # run tests sequentially
            max-parallel: 1
            fail-fast: false
            matrix:
                container: [
                        "centos:stream10",
                ]
                test: [ "40" ]
                include:
                  - network: ""
        container:
            image: ghcr.io/${{ github.repository_owner }}/${{ matrix.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v4
            -   name: "${{ matrix.container }} TEST-${{ matrix.test }}"
                run: USE_NETWORK=${{ matrix.network }} ./tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
